version: '3'
services:
  web:
    image: rochimfn/qa:latest
    build: .
    restart: "unless-stopped"
    ports:
      - "8000:8000"
    entrypoint: python web.py

  bot:
    image: rochimfn/qa:latest
    restart: "unless-stopped"
    volumes:
      - qa-data:/app/.cache/data
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - QA_HOST=web
      - NUM_RANK=1
    entrypoint: python bot.py
    depends_on:
      - db



volumes:
  qa-data:
